name: Quality Checks
permissions:
  contents: read

on:
  workflow_call:

jobs:

  linting:
    uses: ./.github/workflows/_node-job.yml
    with:
      name: 🧹  Linting
      run: pnpm lint

  typeCheck:
    uses: ./.github/workflows/_node-job.yml
    with:
      name: 🔍  Type Check
      run: pnpm typecheck

  unitTest:
    uses: ./.github/workflows/_node-job.yml
    with:
      name: 🧪  Unit Test
      run: pnpm test:unit
      timeout-minutes: 15

  unusedDependencies:
    uses: ./.github/workflows/_node-job.yml
    with:
      name: 📦  Unused Dependencies Check
      run: pnpm dlx knip --include dependencies