name: "Pull Request Validation"

on:
  pull_request:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: write

jobs:
  install-dependencies:
    name: 💾 Install Dependencies
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Dependencies and pre-cache
        uses: ./.github/actions/setup-node-pnpm

  quality-checks:
    needs: install-dependencies
    uses: ./.github/workflows/_quality-checks.yml
